---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cobalt-bazzite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  # Install desired dnf packages
  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
    install:
      packages:
        - code                                    
        - fedora41-flashgbx-4.3-1.fc41.noarch.rpm
        
  # brew install
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    auto-upgrade: true
    upgrade-interval: "7d"

  # Install pyenv
  - type: script
    snippets:
      - "curl -fsSL https://pyenv.run | bash"

  # Flatpacks
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox